# Generated by Django 3.2.9 on 2021-12-28 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20211228_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='roomAddress',
            new_name='room_address',
        ),
        migrations.RenameField(
            model_name='classroom',
            old_name='roomLoad',
            new_name='room_load',
        ),
        migrations.RenameField(
            model_name='classroom',
            old_name='roomNumber',
            new_name='room_number',
        ),
        migrations.AlterField(
            model_name='classroomorder',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='course.classroom', verbose_name='预约课室'),
        ),
    ]
